name: Deploy to gh-pages
on:
  push:
    branches:
      - master
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run Tests
        run: |
          npm run test
      - name: Deploy
        run: |
          git config user.name "jehielmartinez" && git config user.email "jehielmartinez@gmail.com"
          npm run deploy